#!/bin/sh

if [ -x /usr/local/bin/ctop ]; then
  exit
fi

sudo wget https://github.com/bcicen/ctop/releases/download/v0.7.5/ctop-0.7.5-linux-amd64 -O /usr/local/bin/ctop
sudo chmod +x /usr/local/bin/ctop
