#!/bin/sh

SCRIPT_DIR="$(realpath $(dirname "$0"))"

if [ "$(id -u)" -ne 0 ]; then
  echo "this script must be run by root" >&2
  exit 1
fi

pacman -Sy
yes | pacman -S --needed --noconfirm $(cat "${SCRIPT_DIR}/packages/core")
