#!/bin/sh

# navigation
alias -- -="cd -"
alias ..="cd .."

# color
alias ls="ls --color=auto"
alias l.="ls -d .* --color=auto"
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

# confirmation/verbose
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -Iv --preserve-root"
alias ln="ln -iv"
alias chgrp="chgrp --preserve-root"
alias chmod="chmod --preserve-root"
alias chown="chown --preserve-root"

# custom
alias vi="nvim"
alias vim="nvim"
