#!/bin/sh

script_dir="$(dirname "$0")"
package_base_file="$script_dir/.base_packages"

packages_base() {
  sort "$package_base_file"
}

packages_installed() {
  dpkg --list | awk '{print $2}' | sed 's/:.*//' | tail +6 | sort
}

missing_packages() {
  base=$(mktemp)
  installed=$(mktemp)
  packages_base >"$base"
  packages_installed >"$installed"
  comm -23 "$base" "$installed"
  rm "$base" "$installed" >/dev/null 2>&1
}

packages=$(missing_packages)

if [ "$packages" != "" ]; then
  sudo apt-get update
  sudo apt-get install -y $packages
fi
