#!/bin/sh
has_docker="$(dpkg --list | awk '{print $2}' | sed 's/:.*//' | tail +6 | grep docker)"

if [ "$has_docker" != "" ]; then
  exit
fi

distro="$(cat /etc/os-release | grep ^ID= | sed 's/^ID=//')"

sudo apt-get update

sudo apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg \
  lsb-release

curl -fsSL "https://download.docker.com/linux/$distro/gpg" | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] "https://download.docker.com/linux/$distro" \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null

sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
